[package]
name = "client-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
crossterm = "0.27"
ratatui = { version = "0.26", default-features = false, features = ["crossterm"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "net", "time", "sync"] }
client-core = { path = "../client-core" }
client-udp = { path = "../client-udp" }

