[platformio]
default_envs = esp32dev-ptcan

[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
monitor_filters = esp32_exception_decoder

[env:esp32dev-ptcan]
build_flags =
  -DCAN_BPS=500000
  -DCAN_TX=13
  -DCAN_RX=5
  -DUDP_PORT=45454
  -DUDP_HOST=\"192.168.1.5\"

[env:esp32dev-kcan]
build_flags =
  -DCAN_BPS=100000
  -DCAN_TX=13
  -DCAN_RX=5
  -DUDP_PORT=45454
  -DUDP_HOST=\"192.168.1.5\"
